import "./globals.css";
// import styles from "./layout.module.css";
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "Tesla Clon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className={"header"}>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
